# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Add execution permission to gradlew
        run: chmod +x /home/runner/work/demo300/demo300/gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Check Build log
        run:
          echo "you success build"
      # Gradle test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test
      - name: Check Build log
        run:
          echo "you success build"

      - name: Only success
        if: success()
        run:
          echo "operated"
          cd demo300
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Stop"
          git push


      #- name: GitHub Actions Bot
      #  uses: actions/github-script@v6
      #  with:
      #      github-token: ${{ secrets.GITHUB_TOKEN }}
      #      script: |
      #        // Your GitHub Actions bot logic here
      #        core.info("Hello from GitHub Actions bot!");


      #- name: A. 테스트 결과를 PR에 코멘트로 등록합니다
      #  uses: EnricoMi/publish-unit-test-result-action@v2
      #  if: always()
      #  with:
      #    files: build/test-results/**/*.xml





        
